### ISSUE TITLE
Unable to compile a "c" file

### ISSUE THREAD

**Issue by Syneltec** [openlab-vn-ua/NanoWin32#2]
Context : Using linux eclipse gcc-8.3.0 (option -32), libc6-2.28 (multilib(i386)), building a linux 32bits native application on AMD64, x86_64 machine.

Compiling any c++ file is OK
Compiling any c file  gives error(s) in StrConverter, which requires "string" include
- Is NanoWin usable for "c" files/projects (I think yes)
- Do I forget something ? (a #define, a (pre-) #include,....)
- i Is it a bug ?

Your idea of making this project is very good. I plan use it in a realtime application, which I plan port to linux (with xenomai/cobalt) from windows/rtx8
I would need to add some win32 functions, and perhaps, contribute in the project 
(if I go forward)

Thanks in advance for your reply.
Charly.

**Comment by SergeAgeyev** [comment]
Hi, 
Thanks for pointing this out!
We just fixed this issue.
We also added unit test to check compilation test from pure C.

**Comment by Syneltec** [comment]
Hi Serge;
Thanks for your answer.

I observed that C is relatively good supported, and/or in way to be.
For now, I temporary had done some modifications (not clean/publishable :-).

I will soon try your fixes.
Thanks again.
Charly.
